name: Change Working Dir & Shell
on: 
  workflow_dispatch
  # [push]
defaults:  # Workflow Level defaults
  run:
    shell: bash
jobs:
  show-working-directory-linux:
    runs-on: ubuntu-latest
    steps:
      - name: 현재 워킹디렉토리에서 파일 목록 보기 (리눅스)
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPAC
  show-working-directory-win:
    runs-on: windows-latest
    defaults:  # Job Level Defaults
        run:
            shell: pwsh
    steps: 
      - name: 현재 워킹디렉토리에서 파일 목록 보기 (윈도우)
        run: |
          Get-Location
          dir
          echo $env:GITHUB_SHA
          echo $env:GITHUB_REPOSITORY
          echo $env:GITHUB_WORKSPACE

      - name: 파이썬 쉘 
        shell: python  # Step Level Default Shell
        run: |
          import platform 
          print(platform.processor())