name: first-exercise-workflow
on: workflow_dispatch
# [push]

jobs: 
  shell-cmd-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: python version
        run: |
           python --version
           pip --version