name: multi-shell-workflow
on: [push] 
defaults: 
  run: 
    shell: bash

jobs: 
  shell-bash: 
    runs-on: ubuntu-latest
    steps: 
      - name: bash에서 uname -a 출력
        run: 
          uname -a
  shell-pwsh-python-node: 
    runs-on: windows-latest
    defaults: 
      run:
        shell: pwsh
    steps: 
      - name: pwsh에서 Get-ComputerInfo 출력
        run: 
          Get-ComputerInfo
      - name: python에서 sys.version 출력
        shell: python
        run: |
          import sys   
          print(sys.version)
      - name: node에서 process.version 출력
        run: |
          node -e "console.log(process.version)"